### ISSUE TITLE
Hidin elements from the result tree

### ISSUE THREAD

**Issue by p-jakubczyk** [evilsloth/gitlab-ce-tools#12]
It would be an awesome feature to be able to somewhat "edit" contents of the search result.
What I have in mind: select an item from the result tree > right mouse click > Hide/Remove from the list. Such element would be removed from the currently displayed result. It would help with filtering-out "missed hits" from the result tree.
PS: Of course such removed/hidden elements would come back after the search is executed againg.

**Comment by evilsloth** [comment]
Added in 0.14.1. Feature must be enabled in settings menu (it's disabled by default).
It adds an icon next to search result element that allows to hide it from results. There is also an option to clear hidden elements at the the teop of the search results.
