### ISSUE TITLE
Expand and expand all

### ISSUE THREAD

**Issue by p-jakubczyk** [evilsloth/gitlab-ce-tools#7]
It would be very convinient to have "Expand all" option (for all elements on the list) and "Expand" option (available from the 'right mouse button' click) for selected element.
Pretty please :-)

**Comment by evilsloth** [comment]
- "Expand all" added but it might take some time to expand bigger trees as it expands one level at a time. It was the only way (at least that I know of) to prevent exceeding of JS recursion/call stack.
- Expand for an expandable element (project or directory) added when title is double clicked. I hope this solution is agreeable as I find it more convenient (but it might be somewhat hidden for a user).

**Comment by p-jakubczyk** [comment]
Works like a charm, thanks!
